name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual runs from GitHub UI

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config lfs.allowincompletepush true
          git push --force https://NiharRanjanChetia:$HF_TOKEN@huggingface.co/spaces/NiharRanjanChetia/aero-analyst-ai main
